config/routes.rb
Rails.application.routes.draw do
  resources :administrators, only: :create do
    post :login, on: :collection
    post :logout, on: :collection
  end

  namespace :admin do
    resources :challenges do
      post 'open_voting', on: :member
      post 'next_round', on: :member
      post 'reset', on: :member
    end
  end

  resources :challenges, only: :show do
    resources :participants, only: :create
    resources :votes, only: :update
    resources :proposed_solutions
  end

  get :privacy, controller: :home

  root to: "home#index"
end

app/models/proposed_solution.rb
class ProposedSolution < ApplicationRecord
  has_many :votes

  def total_score
    @total_score ||= calculate_total_score
  end

  def calculate_total_score
    all_votes = self.votes.map {|v| v.vote}.compact
    if all_votes.size == 0
      0
    else
      all_votes.sum * 5 / all_votes.size
    end
  end
end

app/controllers/proposed_solutions_controller.rb
class ProposedSolutionsController < ApplicationController
  before_action :set_challenge
  before_action :set_proposed_solution, only: [:show, :edit, :update, :destroy]

  # GET /proposed_solutions
  # GET /proposed_solutions.json
  def index
    @proposed_solutions = ProposedSolution.all
  end

  # GET /proposed_solutions/1
  # GET /proposed_solutions/1.json
  def show
  end

  # GET /proposed_solutions/new
  def new
    @proposed_solution = ProposedSolution.new
  end

  # GET /proposed_solutions/1/edit
  def edit
  end

  # POST /proposed_solutions
  # POST /proposed_solutions.json
  def create
    @proposed_solution = ProposedSolution.new(proposed_solution_params)

    respond_to do |format|
      if @proposed_solution.save
        format.html { redirect_to [@challenge], notice: 'Proposed solution was successfully created.' }
        format.json { render :show, status: :created, location: @proposed_solution }
      else
        format.html { render :new }
        format.json { render json: @proposed_solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposed_solutions/1
  # PATCH/PUT /proposed_solutions/1.json
  def update
    respond_to do |format|
      if @proposed_solution.update(proposed_solution_params)
        format.html { redirect_to [@challenge], notice: 'Proposed solution was successfully updated.' }
        format.json { render :show, status: :ok, location: @proposed_solution }
      else
        format.html { render :edit }
        format.json { render json: @proposed_solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposed_solutions/1
  # DELETE /proposed_solutions/1.json
  def destroy
    @proposed_solution.destroy
    respond_to do |format|
      format.html { redirect_to proposed_solutions_url, notice: 'Proposed solution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find_by_external_id(params[:challenge_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_proposed_solution
      @proposed_solution = ProposedSolution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proposed_solution_params
      params.require(:proposed_solution).permit(:narrative, :first_step).merge(
        participant_id: session[:participant_id],
        challenge_id: @challenge.id
      )
    end
end

app/helpers/proposed_solutions_helper.rb
module ProposedSolutionsHelper
end

app/views/proposed_solutions/_form.html.erb
<%= form_with(model: [@challenge, proposed_solution], local: true) do |form| %>
  <% if proposed_solution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proposed_solution.errors.count, "error") %> prohibited this proposed_solution from being saved:</h2>

      <ul>
        <% proposed_solution.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :challenge_id %>
    <%= form.text_field :challenge_id %>
  </div>

  <div class="field">
    <%= form.label :narrative %>
    <%= form.text_field :narrative %>
  </div>

  <div class="field">
    <%= form.label :first_step %>
    <%= form.text_field :first_step %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proposed_solutions/edit.html.erb
<h1>Editing Proposed Solution</h1>

<%= render 'form', proposed_solution: @proposed_solution %>

<%= link_to 'Show', @proposed_solution %> |
<%= link_to 'Back', proposed_solutions_path %>

app/views/proposed_solutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proposed Solutions</h1>

<table>
  <thead>
    <tr>
      <th>Challenge</th>
      <th>Narrative</th>
      <th>First step</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proposed_solutions.each do |proposed_solution| %>
      <tr>
        <td><%= proposed_solution.challenge_id %></td>
        <td><%= proposed_solution.narrative %></td>
        <td><%= proposed_solution.first_step %></td>
        <td><%= link_to 'Show', proposed_solution %></td>
        <td><%= link_to 'Edit', edit_proposed_solution_path(proposed_solution) %></td>
        <td><%= link_to 'Destroy', proposed_solution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proposed Solution', new_proposed_solution_path %>

app/views/proposed_solutions/new.html.erb
<h1>New Proposed Solution</h1>

<%= render 'form', proposed_solution: @proposed_solution %>

<%= link_to 'Back', proposed_solutions_path %>

app/views/proposed_solutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Challenge:</strong>
  <%= @proposed_solution.challenge_id %>
</p>

<p>
  <strong>Narrative:</strong>
  <%= @proposed_solution.narrative %>
</p>

<p>
  <strong>First step:</strong>
  <%= @proposed_solution.first_step %>
</p>

<%= link_to 'Edit', edit_proposed_solution_path(@proposed_solution) %> |
<%= link_to 'Back', proposed_solutions_path %>