config/routes.rb
Rails.application.routes.draw do
  resources :administrators, only: :create do
    post :login, on: :collection
    post :logout, on: :collection
  end

  namespace :admin do
    resources :challenges do
      post 'open_voting', on: :member
      post 'next_round', on: :member
      post 'reset', on: :member
    end
  end

  resources :challenges, only: :show do
    resources :participants, only: :create
    resources :votes, only: :update
    resources :proposed_solutions
  end

  get :privacy, controller: :home

  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_administrator

  def index
  end

  def privacy
  end

  def set_administrator
    if session[:administrator_id]
      @administrator = Administrator.find_by_administrator_id!(session[:administrator_id])
    end
  rescue ActiveRecord::RecordNotFound
    session.delete(:administrator_id)
    redirect_to "/", notice: "Administrator not found"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">25/10 Crowdsourcing</h1>

<p class="subhead">Rapidly generate and sift a group’s most powerful actionable ideas</p>

<p>A tool to support <a href="http://www.liberatingstructures.com/12-2510-crowd-sourcing/">25/10 Crowdsourcing</a> virtually by <a href="https://ko-fi.com/twentyfivetenapp">David Heath</a>.</p>

<% if ENV.has_key?("SETUP_BY") %>
  <h2 class="operator">This installation was set up by <%= ENV['SETUP_BY'] %></h2>
<% end %>

<p>You can run your own installation for free on Heroku by clicking this button:
  <a href="https://heroku.com/deploy?template=https://github.com/heathd/twentyfiveten">
  <img src="https://www.herokucdn.com/deploy/button.svg" alt="Deploy">
</a>

<h2>What is 25/10 Crowdsourcing?</h2>

<p>25/10 Crowdsourcing is way for a group to generate and prioritise ideas quickly. It's part of the <a href="http://www.liberatingstructures.com/">Liberating Structures</a> repertoire.</p>

<p>You start by presenting a challenge to a group and then inviting each person to come up with one bold idea to address it. Each person writes their idea on a card and the ideas are then scored anonymously five times by five different people. At the end of the process the scores are totalled and the top scoring ideas surfaced through a reverse-auction (<a href="http://www.liberatingstructures.com/12-2510-crowd-sourcing/">full description of 25/10 Crowdsourcing</a>). </p>

<p>Doing this process online is tricky, as it's hard to shuffle the ideas and also hard to anonymise the scoring process. This app is designed to help with that!</p>

<h2>How it works</h2>

<p>To use this tool you need a group of people dialled into a call at the same time, as you'll need to tell people when it's time to start voting and to move from one round of voting to the next.</p>

<ol>
  <% if @administrator %>
    <li>Register as an administrator (you're already registered!)</li>
    <li><%= link_to "Create your challenge", new_admin_challenge_path %></li>
  <% else %>
    <li>Register as an administrator (see below)</li>
    <li>Create your challenge</li>
  <% end %>

  <li>Invite participants to propose their solutions, by sharing the unique <em>challenge URL</em> with them</li>
  <li>Wait for all particpants to register and submit their proposals (you'll need to refresh your admin screen to see the numbers change). Once all proposals have been received, you can Open voting. Once voting is open, no new participants can join.</li>
  <li>When voting is open, participants must click to see their first idea to vote on. As the administrator you'll see how many votes have been cast. When you are happy that all votes are cast, you can advance to the next round. If you're doing the activity via video call, you may want to play some music and invite participants to move around to the music for a short while.</li>
  <li>Repeat until all five rounds are complete. You can then close the voting.</li>
  <li>When voting is closed everyone can see the summary. Votes are totalled automatically. If votes were missing for some ideas, then a score out of 25 is extrapolated from the votes that were cast by taking the average score and multiplying by 5.</li>
  <li>That's it!</li>
</ol>

<p>All voting and administration is anonymous. Your identity and that of participants is tracked using a browser cookie <code>_twentyfiveten_session</code>. Participants can only participate in one challenge at a time.</p>

<p>If you find this useful, <a href="https://ko-fi.com/twentyfivetenapp">buy me a coffee</a>.</p>

<h3>Screenshots</h3>
<div class="screenshots">

<a href="/screenshots/full/02 - New challenge.png"><img src="/screenshots/thumbs/02 - New challenge.png" /></a>
<a href="/screenshots/full/03 - list challenges.png"><img src="/screenshots/thumbs/03 - list challenges.png" /></a>
<a href="/screenshots/full/04 - participate.png"><img src="/screenshots/thumbs/04 - participate.png" /></a>
<a href="/screenshots/full/05 - Submit idea.png"><img src="/screenshots/thumbs/05 - Submit idea.png" /></a>
<a href="/screenshots/full/05b - Submit idea.png"><img src="/screenshots/thumbs/05b - Submit idea.png" /></a>
<a href="/screenshots/full/05c - Submit idea.png"><img src="/screenshots/thumbs/05c - Submit idea.png" /></a>
<a href="/screenshots/full/06 - idea submitted.png"><img src="/screenshots/thumbs/06 - idea submitted.png" /></a>
<a href="/screenshots/full/07 - admin waiting for participants.png"><img src="/screenshots/thumbs/07 - admin waiting for participants.png" /></a>
<a href="/screenshots/full/07b - administrator opens voting.png"><img src="/screenshots/thumbs/07b - administrator opens voting.png" /></a>
<a href="/screenshots/full/08 - participant casts vote.png"><img src="/screenshots/thumbs/08 - participant casts vote.png" /></a>
<a href="/screenshots/full/08b - participant casts vote.png"><img src="/screenshots/thumbs/08b - participant casts vote.png" /></a>
<a href="/screenshots/full/09 - admin opens next voting round.png"><img src="/screenshots/thumbs/09 - admin opens next voting round.png" /></a>
<a href="/screenshots/full/10 - admin concludes voting.png"><img src="/screenshots/thumbs/10 - admin concludes voting.png" /></a>
<a href="/screenshots/full/10b - admin concludes voting.png"><img src="/screenshots/thumbs/10b - admin concludes voting.png" /></a>
<a href="/screenshots/full/11 - summary of results.png"><img src="/screenshots/thumbs/11 - summary of results.png" /></a>

</div>

<p><a href="https://github.com/heathd/twentyfiveten/blob/master/README.md">More in readme</a></p>

<h3>No warranty</h3>

<p>This service is a protype and is offered as-is without warranty of any kind, express or implied, including but not limited to the warranties of merchantibility or fitness for a particular purpose. Source code is available on <a href="https://github.com/heathd/twentyfiveten">github</a> under a <a href="https://github.com/heathd/twentyfiveten/blob/master/LICENSE">GNU Affero General Public License v3.0</a>.</p>

<h3>Feedback</h3>

<p>If you have a chance to try this out with a group and collect some feedback, I would love to hear about it. I'm particulary interested in:</p>

<ul>
  <li>Participants experience -- could participants understand what to do and how to participate without needing lots of instructions or guidance? Were there things that caused confusion which could be clearer?</li>
  <li>Administrator's experience -- as an administrator, could you understand how the overall process would work before you started, enough to be confident that you could facilitate the process? Did everything go smoothly? Did you get a useful/practical outcome from your crowdsourcing? Did you play music between each round, if so, how was that? If not, why not? What do you think about the synchronous voting?</li>
</ul>

<p>You can give me feedback in these ways:</p>

<ul>
  <li>Email me on david at davidheath dot org</li>
  <li>Open an <a href="https://github.com/heathd/twentyfiveten/issues">issue on github</a>.</li>
</ul>


<h3 id="privacy">Privacy and data protection</h3>

<p>This application will store and process your data, and data submitted by your participants for the purpose of offering you the 25/10 crowdsourcing service. The lawful basis for processing your data is <b>consent</b>. </p>

<p>This application does not explicitly collect any personal data. You and your participants choose what data you submit.</p>

<p>We process and store your data securely in Heroku. Read <a href="https://www.heroku.com/policy/security">Heroku's security and privacy policy</a></p>

<p><strong>Data will be deleted after 30 days.</strong></p>

<p>If you wish to retain your data please copy/paste and save it elsewhere.</p>

<h2 id="admin-links">Administrator links</h2>

<% if @administrator %>
  <p>Your administrator login code: <%= @administrator.administrator_id %></p>
  <p><%= link_to "View all of your challenges", [:admin, :challenges] %></p>
  <p><%= link_to "Create a challenge", new_admin_challenge_path %></p>

  <%= button_to "Logout", logout_administrators_path %>

<% else %>

  <%= button_to "I consent to the processing of my data, register me as an administrator", [:administrators], action: :create, class: "button-primary"%>

  <p>or</p>
  <h2>Login using an administrator code</h2>
  <%= form_tag login_administrators_path, :method => :post do %>
    <%= label_tag :administrator_id, "Administrator ID" %>
    <%= text_field_tag :administrator_id %>
    <%= submit_tag 'Login' %><br />
  <% end %>
<% end %>

app/views/home/privacy.html.erb
<h1>Twenty Five Ten Crowdsourcing</h1>

<h2>Privacy and data protection</h2>

<p>This application will store and process your data in order to offer the 25/10 crowdsourcing service. The lawful basis for processing your data is <b>consent</b>. </p>

<p>All voting and administration is anonymous. Your identity is tracked using a browser cookie <code>_twentyfiveten_session</code>.</p>

<p>This application does not explicitly collect any personal data. You choose what data to submit. We process and store your data securely in Heroku (read <a href="https://www.heroku.com/policy/security">Heroku's security and privacy policy</a>).</p>

<p><strong>Your data will be deleted after 30 days.</strong></p>

<p>If you wish to retain your data please copy/paste and save it elsewhere.</p>