config/routes.rb
Rails.application.routes.draw do
  resources :administrators, only: :create do
    post :login, on: :collection
    post :logout, on: :collection
  end

  namespace :admin do
    resources :challenges do
      post 'open_voting', on: :member
      post 'next_round', on: :member
      post 'reset', on: :member
    end
  end

  resources :challenges, only: :show do
    resources :participants, only: :create
    resources :votes, only: :update
    resources :proposed_solutions
  end

  get :privacy, controller: :home

  root to: "home#index"
end

app/models/administrator.rb
require 'securerandom'

class Administrator < ApplicationRecord

  before_create do
    self.administrator_id = random_id(14) if administrator_id.blank?
  end

  def random_id(length)
    SecureRandom.alphanumeric(length)
  end
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :clear_stale_session, only: [:create]
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  def login
    params.require(:administrator_id)
    @administrator = Administrator.find_by_administrator_id(params[:administrator_id])
    if @administrator
      session[:administrator_id] = @administrator.administrator_id
      redirect_to admin_challenges_path, notice: "Logged in successfully"
    else
      redirect_to root_path, notice: 'Administrator not found'
    end
  end

  def logout
    session.delete(:administrator_id)
    redirect_to root_path, notice: 'Logged out'
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    if session[:administrator_id].present?
      redirect_to admin_challenges_path
    else
      @administrator = Administrator.new(administrator_params)
    end

    respond_to do |format|
      if @administrator.save
        session[:administrator_id] = @administrator.administrator_id
        format.html { redirect_to admin_challenges_path, notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def clear_stale_session
      if session[:administrator_id].present?
        @administrator = Administrator.find_by_administrator_id!(session[:administrator_id])
      end
    rescue ActiveRecord::RecordNotFound
      session.delete(:administrator_id)
    end

    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def administrator_params
      params.permit()
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= form_with(model: administrator, local: true) do |form| %>
  <% if administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
        <% administrator.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :administrator_id %>
    <%= form.text_field :administrator_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form', administrator: @administrator %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Administrators</h1>

<table>
  <thead>
    <tr>
      <th>Administrator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.administrator_id %></td>
        <td><%= link_to 'Show', administrator %></td>
        <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrator', new_administrator_path %>

app/views/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form', administrator: @administrator %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Administrator:</strong>
  <%= @administrator.administrator_id %>
</p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>