config/routes.rb
Rails.application.routes.draw do
  resources :administrators, only: :create do
    post :login, on: :collection
    post :logout, on: :collection
  end

  namespace :admin do
    resources :challenges do
      post 'open_voting', on: :member
      post 'next_round', on: :member
      post 'reset', on: :member
    end
  end

  resources :challenges, only: :show do
    resources :participants, only: :create
    resources :votes, only: :update
    resources :proposed_solutions
  end

  get :privacy, controller: :home

  root to: "home#index"
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :participant
  belongs_to :proposed_solution
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_challenge, only: [:update]
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to [@challenge], notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { redirect_to [@challenge], notice: 'Error casting vote.'  }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find_by_external_id!(params[:challenge_id])
    end

    def set_vote
      @vote = Vote.where(participant_id: session[:participant_id]).find(params[:id])
    end

    def vote_params
      params.require(:vote).permit(:vote)
    end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_with(model: vote, local: true) do |form| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
        <% vote.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :challenge_id %>
    <%= form.text_field :challenge_id %>
  </div>

  <div class="field">
    <%= form.label :proposed_solution_id %>
    <%= form.text_field :proposed_solution_id %>
  </div>

  <div class="field">
    <%= form.label :participant_id %>
    <%= form.text_field :participant_id %>
  </div>

  <div class="field">
    <%= form.label :vote %>
    <%= form.text_field :vote %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Votes</h1>

<table>
  <thead>
    <tr>
      <th>Challenge</th>
      <th>Proposed solution</th>
      <th>Participant</th>
      <th>Vote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.challenge_id %></td>
        <td><%= vote.proposed_solution_id %></td>
        <td><%= vote.participant_id %></td>
        <td><%= vote.vote %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Challenge:</strong>
  <%= @vote.challenge_id %>
</p>

<p>
  <strong>Proposed solution:</strong>
  <%= @vote.proposed_solution_id %>
</p>

<p>
  <strong>Participant:</strong>
  <%= @vote.participant_id %>
</p>

<p>
  <strong>Vote:</strong>
  <%= @vote.vote %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>